### ISSUE TITLE
Syndie Recon Outpost spawned with breaches

### ISSUE THREAD

**Issue by Ralta** [OracleStation/OracleStation#607] opened 2018-02-11 23:11 UTC
See: https://i.imgur.com/0U6HCZy.png

Two gaps in the base itself; apparently started there. Telecomms had no power either - assuming it's missing an APC or powernet link somewhere?

**Comment by ike709** [comment] 2018-02-11 23:13
Dupe of #590

**Comment by SamHPurp** [comment] 2018-02-12 17:38
Duplicate of #590

**Closed by SamHPurp** 2018-02-12 17:38 UTC
