### ISSUE TITLE
Unable to dig lavaland floors

### ISSUE THREAD

**Issue by Quantum-M** [OracleStation/OracleStation#325] opened 2017-11-26 21:37 UTC
While in lavaland, I was unable to dig up any of the dirt tiles (volcanic rock that is) to get any sand. I tried both a pickax and a shovel (and even with a crowbar) with no results.

**Comment by imsxz** [comment] 2017-11-26 23:12
nanotrasen packed some extra tough basalt for the miners this time

**Comment by Quantum-M** [comment] 2017-11-26 23:23
Clearly, they won't want NT to see the true nature of lavaland... (#324)

**Comment by SamHPurp** [comment] 2017-11-27 00:15
Duplicate of #324

**Closed by SamHPurp** 2017-11-27 00:15 UTC
