### ISSUE TITLE
Heat Exchange Junction Fitting Missing Texture When Created From Pipe Dispenser or RPD

### ISSUE THREAD

**Issue by wrightcameron** [OracleStation/OracleStation#939] opened 2018-06-01 06:18 UTC
[Round ID]: # 2627

Was using the Rapid Piping Device (RPD) to create a heat exchange and when I went to create a junction piece it creates it but does not have a texture.  The item is created because right clicking lists the item on the tile and can be picked up through right clicking.  The lack of texture though makes wrenching the pipe impossible.

**Steps to Reproduce:**
1. Get RPD or use pipe dispenser.
2. Click function under heat exchange section.

**Actual Results:**
Junction Fitting is spawned but missing texture.

**Expected Results:**
Junction fitting should not be missing its texture.

**Comment by AffectedArc07** [comment] 2018-06-01 07:59
If you want a ghetto workaround, to actually be able to wrench down, alt click the time, look in the top right and click the text saying junction fitting

**Comment by AndrewMontagne** [comment] 2018-08-13 17:53
Duplicate of #756

**Closed by AndrewMontagne** 2018-08-13 17:53 UTC
Labels: Bug
