### ISSUE TITLE
Wallet disappearing

### ISSUE THREAD

**Issue by Rustybuckets6601** [OracleStation/OracleStation#1146] opened 2018-08-09 06:35 UTC
If you put your ID into a wallet, it turns invisible, even if you were to drop it. Doesn't matter if the wallet is full or empty, putting an ID into it turns it invisible. Removing the ID makes it visible again.

**Comment by AndrewMontagne** [comment] 2018-08-13 17:51
Duplicate of #837

**Closed by AndrewMontagne** 2018-08-13 17:51 UTC
