### ISSUE TITLE
Cargo Shuttle never docks

### ISSUE THREAD

**Issue by Birdtalon** [OracleStation/OracleStation#83] opened 2017-09-28 21:14 UTC
Cargo shuttle can be called but never actually properly docks.

Requires further testing to pin down. Runtime related as far as I know so far. I will update upon further testing.

**Comment by FlattestGuitar** [comment] 2017-09-29 09:04
Likely a duplicate of #64

I'll close this for now.

**Closed by FlattestGuitar** 2017-09-29 09:04 UTC

**Comment by SamHPurp** [comment] 2017-09-29 09:14
@FlattestGuitar I think you've set the wrong thing as 'duplicate of'.... thats LOOC....

But that said, I've solved the cargo problem, just sorting my repo out...
