### ISSUE TITLE
Bug with Genetics.

### ISSUE THREAD

**Issue by Tatsu500** [OracleStation/OracleStation#570] opened 2018-02-06 21:12 UTC
Issue reported from Round ID: 580 (Oracle Station | Medium RP)

Hi i just wanted to say that genetics has some bugs on the Meta Station, when i transform a monkey into a human, i experiment with the bodies, the SE does not show up.

And if i already have a human to experiment, when i change the SE it has no effect.

**Comment by AndrewMontagne** [comment] 2018-02-06 21:15
Duplicate of #488

**Closed by AndrewMontagne** 2018-02-06 21:15 UTC
