### ISSUE TITLE
Wallet and mining ID

### ISSUE THREAD

**Issue by Tatsu500** [OracleStation/OracleStation#1003] opened 2018-06-23 12:02 UTC
Issue reported from Round ID: 3034 (Oracle Station | Medium RP)

This one is simple, i was a free golem and i made a wallet, when i put my mining id in it, both of them dissapeared. I don't think its a visual bug, because i tried cliclking on the ground to see if i was invisible, but nope, they just vanished.

**Comment by FlattestGuitar** [comment] 2018-06-23 12:19
You can't click invisible objects, because they have no hitbox. You can alt+click on a tile to see a list of its contents (or just right click). Have you done one of the latter to make sure that the wallet was not there? Alternatively, if it was in your hand or the ID slot. We'd want to know what happens there, exactly.

**Comment by Affurit** [comment] 2018-06-23 13:44
The wallet wasn't dropped. The issue seems to be that don't have sprites for many of the new ID cards that we've sprited, so as a result of that, when an ID is placed into the ID slot, it goes invisible as the icon is changed into something that doesn't exist? This happens with station ID cards too. 

Later insight after some testing: It happens with all but 2 ID cards on the station.

https://imgur.com/a/fRWkqms

Here you go, flatty.

**Comment by tjg1** [comment] 2018-07-25 23:48
I'm going to make the wallet `icon_state` fallback to `wallet_id` to stop it from disappearing.

Still needs proper sprites.

**Comment by AndrewMontagne** [comment] 2018-08-13 17:51
Duplicate of #837

**Closed by AndrewMontagne** 2018-08-13 17:51 UTC
Labels: Bug
