### ISSUE TITLE
Genetics Manifestations

### ISSUE THREAD

**Issue by threehornes** [OracleStation/OracleStation#562] opened 2018-02-05 22:00 UTC
Issue reported from Round ID: 566 (Oracle Station | Medium RP)

Using spawned in humans, altering SE did nothing. Tried to test 3 SE's that were at e+, and using the injector had no effect aside from radiation. Even occupant:delayed did nothing, so it would appear that the effects, both negative and positive aren't registering.

**Comment by AndrewMontagne** [comment] 2018-02-06 21:15
Duplicate of #488

**Closed by AndrewMontagne** 2018-02-06 21:15 UTC
