### ISSUE TITLE
as a floating posi brain i can hear changling channel. 

### ISSUE THREAD

**Issue by enderman51505** [OracleStation/OracleStation#498] opened 2018-01-30 01:29 UTC
Issue reported from Round ID: 453 (Oracle Station | Medium RP)
i think it happened because i got destroyed as a borg by the ai and since i was made one by surgery while a ipc.

**Comment by Ziiro** [comment] 2018-01-30 02:00
Can confirm this is a reproducible bug:

![dreamseeker_2018-01-29_18-58-04](https://user-images.githubusercontent.com/26494679/35544213-815b3394-0526-11e8-8b8a-ceb5c14f7c4f.png)

I'm working on it, but I make no promises.
@FlattestGuitar this is pretty serious

**Comment by AndrewMontagne** [comment] 2018-02-03 01:37
Duplicate of #501

**Closed by AndrewMontagne** 2018-02-03 01:37 UTC
