### ISSUE TITLE
Invisible heat junction pipes

### ISSUE THREAD

**Issue by Captaincardgage** [OracleStation/OracleStation#827] opened 2018-04-07 17:21 UTC
Round ID: 1683

Players in atmos reported invisible junction pipes, after confirmation it can be proven. Used a Rapid Piping device and tried laying heat junction pipes but their sprites were invisible.

https://i.imgur.com/S2LG05r.png?1

**Comment by The-Driker** [comment] 2018-05-03 04:42
Investigation in game revealed that the pipes are being spawned from the RPD with the icon_state as junction2 instead of junction.

**Comment by AndrewMontagne** [comment] 2018-08-13 17:53
Duplicate of #756

**Closed by AndrewMontagne** 2018-08-13 17:53 UTC
Labels: Bug
