### ISSUE TITLE
Xenobio Mutation toxins are borked

### ISSUE THREAD

**Issue by Ismothers** [OracleStation/OracleStation#1026] opened 2018-07-02 21:28 UTC
Xenobiology mutation toxins are broken. They make you collapse like normal, but there isn't any changing effect. This started once andrew pushed his 'all mutation toxins need 1u' commit

**Comment by AndrewMontagne** [comment] 2018-07-02 22:17
When did you last encounter this? We recently merged a fix for this.

**Comment by SamHPurp** [comment] 2018-07-04 22:18
I can't reproduce, is this now fixed by #1021 ?

**Comment by AndrewMontagne** [comment] 2018-07-05 15:53
If this comes up again we can look into it.

**Closed by AndrewMontagne** 2018-07-05 15:53 UTC
Labels: Bug
